version: '3.8'

services:
 
  db:
    container_name: mysqldb1
    image: mysql/mysql-server:8.0  
    ports:
      - 3306:3306   
    environment:
      - MYSQL_ROOT_PASSWORD=guessitplease
      - MYSQL_DATABASE=carrent
      - MYSQL_USER=root
      - MYSQL_PASSWORD=guessitplease
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --bind-address=0.0.0.0
      - --skip-host-cache
      - --skip-name-resolve
      
    networks:
      - spring 

  eureka-server:
    build:
      context: ./Eureka-server
      dockerfile: Dockerfile
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

    networks:
      - spring
    depends_on:
      - zipkin


  rent-ms:
      build:
        context: ./Rent-MS
      
     
      container_name: rent-MS
      ports:
         - "8080:8080"
      environment:
           SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.110:3306/carrent
           SPRING_DATASOURCE_USERNAME: root
           SPRING_DATASOURCE_PASSWORD: guessitplease
           SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'  

       
      networks:
         - spring
      depends_on:
          - zipkin
          - eureka-server
          - db
          - rabbitmq

  apigw:
      build:
        context: ./api-gateway
        dockerfile: Dockerfile
      image: apigw
      container_name: apigw
      ports:
        - "8081:8081"
      environment:
        SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'  
      networks:
        - spring
      depends_on:
        - zipkin
        - eureka-server

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
      
networks:
 
  spring:
    driver: bridge

volumes:
  mysql:
  pgadmin:
